CREATE TYPE status ENUM ('DELIVERED', 'ONGOING', 'NOT-DELIVERED')

CREATE TABLE IF NOT EXISTS delivery (
    id uuid DEFAULT uuid_generate_v4(),
    status status NOT NULL DEFAULT 'ONGOING',
    date_created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    date_updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY(id)
);